services:
  postgres:
    image: postgres:16
    container_name: postgres_cinema
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345678}
      POSTGRES_DB: ${DB_NAME:-cinema}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - pgdata_cinema:/var/lib/postgresql/data

volumes:
  pgdata_cinema:
